---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - controlplane.noplane.io
  resources:
  - noplanecontrolplanes
  - noplanecontrolplanetemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - controlplane.noplane.io
  resources:
  - noplanecontrolplanes/finalizers
  - noplanecontrolplanetemplates/finalizers
  verbs:
  - update
- apiGroups:
  - controlplane.noplane.io
  resources:
  - noplanecontrolplanes/status
  - noplanecontrolplanetemplates/status
  verbs:
  - get
  - patch
  - update
