apiVersion: controlplane.noplane.io/v1alpha1
kind: NoPlaneControlPlane
metadata:
  labels:
    app.kubernetes.io/name: capi-noplane
    app.kubernetes.io/managed-by: kustomize
  name: noplanecontrolplane-sample
spec:
  version: v1.29.2
  replicas: 1
  credentialsSecretRef:
    name: noplane-credentials
    namespace: default
